### ISSUE TITLE
Semgrep Dashboard Integration

### ISSUE THREAD

**Issue by italo-gouveia** [italo-gouveia/myanimeapi#122]
---
name: Semgrep Dashboard Integration
about: Set up Semgrep Cloud Platform dashboard for security findings
title: "Implement Semgrep Dashboard Integration"
labels: enhancement, security, ci/cd
assignees: ''
---

## Description

Implement Semgrep Cloud Platform dashboard integration to improve security findings management and collaboration.

## Background

Currently, our CI/CD pipeline uses Semgrep for security analysis but doesn't publish results to a centralized dashboard. By integrating with Semgrep Cloud Platform, we can:

- Track security findings over time
- Collaborate with team members on fixing issues
- Reduce false positives
- Get historical analysis of our security posture
- Integrate with GitHub for automated issue creation and PR comments

## Tasks

- [ ] Create a Semgrep Cloud Platform account
- [ ] Generate an API token
- [ ] Add the token as a GitHub secret (`SEMGREP_APP_TOKEN`)
- [ ] Update the CI workflow to publish results:
  ```yaml
  - name: Run Semgrep
    uses: returntocorp/semgrep-action@v1
    with:
      config: p/security-audit
      publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
      publishDeployment: ${{ github.repository_owner }}/myanimeapi
  ```
- [ ] Configure Semgrep to create GitHub issues for critical findings
- [ ] Set up status checks to block merging if critical issues are found
- [ ] Document the Semgrep dashboard integration in the project README

## Benefits

- Centralized security management
- Better collaboration on security issues
- Historical tracking of security posture
- Reduced false positives
- Automated issue creation and PR comments

## References

- [Semgrep Cloud Platform Documentation](https://semgrep.dev/docs/semgrep-cloud-platform/)
- [Semgrep GitHub Action Documentation](https://github.com/returntocorp/semgrep-action)

## Acceptance Criteria

- [ ] Semgrep results are published to the dashboard
- [ ] Team members can access the dashboard
- [ ] Critical findings create GitHub issues automatically
- [ ] PRs with critical issues are blocked from merging
- [ ] Documentation is updated to reflect the new integration
