### ISSUE TITLE
Add initial CI/CD Pipeline (GitHub Actions)

### ISSUE THREAD

**Issue by italo-gouveia** [italo-gouveia/myanimeapi#51]
Add CI/CD Pipeline
Set up a CI/CD pipeline (e.g., GitHub Actions, GitLab CI) to automate testing, linting, and deployment.

Example GitHub Actions workflow:

```yaml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Run tests
        run: go test ./...
```
